"""initial schema

Revision ID: 2347cbabe6c7
Revises:
Create Date: 2026-03-05 15:20:56.566229

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2347cbabe6c7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="importstatus"),
            nullable=False,
        ),
        sa.Column("total_rows", sa.Integer(), nullable=True),
        sa.Column("buyers_count", sa.Integer(), nullable=True),
        sa.Column("contracts_count", sa.Integer(), nullable=True),
        sa.Column("documents_count", sa.Integer(), nullable=True),
        sa.Column("new_buyers", sa.Integer(), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=True),
        sa.Column("delta_summary", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "MANAGER", "VIEWER", name="userrole"), nullable=False),
        sa.Column("telegram_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inn", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
        sa.Column("name_1c", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_display", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "org_type",
            sa.Enum(
                "TSN", "OOO", "AO", "IP", "KP", "ZHK", "SNT", "NP", "FL", "PROCHEE", name="orgtype"
            ),
            nullable=True,
        ),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.Column("client_since", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CHURNED", "SUSPENDED", "PROSPECT", name="orgstatus"),
            nullable=False,
        ),
        sa.Column("objects", sa.Integer(), nullable=True),
        sa.Column("object_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cloud_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("system_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("equipment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city_region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("has_folder", sa.Boolean(), nullable=True),
        sa.Column("payment_score", sa.Integer(), nullable=True),
        sa.Column("monthly_ap", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_debt", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_inn"), "organizations", ["inn"], unique=True)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "alert_type",
            sa.Enum(
                "NON_PAYMENT",
                "CHURN_RISK",
                "LARGE_DEBT",
                "UNASSIGNED_CLIENT",
                "PHANTOM_DEAL",
                "PROJECT_OVERDUE",
                "ANOMALY",
                "COLLECTABILITY_DROP",
                "NEW_CLIENT",
                name="alerttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity", sa.Enum("CRITICAL", "WARNING", "INFO", name="alertseverity"), nullable=False
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metric_value", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "ACKNOWLEDGED", "RESOLVED", "DISMISSED", name="alertstatus"),
            nullable=False,
        ),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("contract_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("contract_date", sa.Date(), nullable=True),
        sa.Column(
            "contract_type",
            sa.Enum("SUBSCRIPTION", "EQUIPMENT", "SERVICE", "OTHER", name="contracttype"),
            nullable=False,
        ),
        sa.Column("classification_source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("classification_rule", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("monthly_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "TERMINATED", name="contractstatus"),
            nullable=False,
        ),
        sa.Column("raw_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contracts_organization_id"), "contracts", ["organization_id"], unique=False
    )
    op.create_table(
        "monthly_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("debt_start", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("advance_start", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("sold", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("paid", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("sold_ap", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("paid_ap", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("sold_equip", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("paid_equip", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("debt_end", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("advance_end", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("plan_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("collectability", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("dso", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("import_run_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_run_id"],
            ["import_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "year", "month", "import_run_id"),
    )
    op.create_index(
        op.f("ix_monthly_snapshots_organization_id"),
        "monthly_snapshots",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum("SALE", "PAYMENT", "PREPAY_IN", "PREPAY_USED", name="doctype"),
            nullable=False,
        ),
        sa.Column("doc_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("doc_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=True),
        sa.Column("period_month", sa.Integer(), nullable=True),
        sa.Column("import_run_id", sa.Uuid(), nullable=True),
        sa.Column("raw_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_run_id"],
            ["import_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_contract_id"), "documents", ["contract_id"], unique=False)
    op.create_index(
        op.f("ix_documents_organization_id"), "documents", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_organization_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_contract_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_monthly_snapshots_organization_id"), table_name="monthly_snapshots")
    op.drop_table("monthly_snapshots")
    op.drop_index(op.f("ix_contracts_organization_id"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_organizations_inn"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("import_runs")
    # ### end Alembic commands ###
