"""add doc_exchange to organizations

Revision ID: 884c0b6f21df
Revises: 47ecf1978b59
Create Date: 2026-05-14 15:36:26.893119

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "884c0b6f21df"
down_revision: Union[str, Sequence[str], None] = "47ecf1978b59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column("doc_exchange", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "doc_exchange")
    # ### end Alembic commands ###
