"""ar ledger tables

Revision ID: 8f49f48e53dc
Revises: f2e86a190626
Create Date: 2026-05-18 15:23:45.899203

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f49f48e53dc"
down_revision: Union[str, Sequence[str], None] = "f2e86a190626"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tariff_periods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("monthly_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tariff_periods_organization_id"),
        "tariff_periods",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "monthly_charges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "source",
            sa.Enum("REALIZATION_1C", "SYNTHETIC_TARIFF", name="chargesource"),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "year", "month", name="uq_charge_org_period"),
    )
    op.create_index(
        op.f("ix_monthly_charges_organization_id"),
        "monthly_charges",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "payment_allocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payment_document_id", sa.Uuid(), nullable=False),
        sa.Column("monthly_charge_id", sa.Uuid(), nullable=True),
        sa.Column("allocated_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "basis",
            sa.Enum("EXPLICIT_PERIOD", "FIFO", "ADVANCE", "MANUAL", name="allocationbasis"),
            nullable=False,
        ),
        sa.Column("is_manual", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monthly_charge_id"],
            ["monthly_charges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_allocations_monthly_charge_id"),
        "payment_allocations",
        ["monthly_charge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_allocations_payment_document_id"),
        "payment_allocations",
        ["payment_document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_payment_allocations_payment_document_id"), table_name="payment_allocations"
    )
    op.drop_index(
        op.f("ix_payment_allocations_monthly_charge_id"), table_name="payment_allocations"
    )
    op.drop_table("payment_allocations")
    op.drop_index(op.f("ix_monthly_charges_organization_id"), table_name="monthly_charges")
    op.drop_table("monthly_charges")
    op.drop_index(op.f("ix_tariff_periods_organization_id"), table_name="tariff_periods")
    op.drop_table("tariff_periods")
    # ### end Alembic commands ###
