"""add excluded_from_analytics

Revision ID: f2e86a190626
Revises: 884c0b6f21df
Create Date: 2026-05-14 16:24:13.011760

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2e86a190626"
down_revision: Union[str, Sequence[str], None] = "884c0b6f21df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "organizations",
        sa.Column(
            "excluded_from_analytics", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "organizations",
        sa.Column("excluded_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_organizations_excluded_from_analytics"),
        "organizations",
        ["excluded_from_analytics"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organizations_excluded_from_analytics"), table_name="organizations")
    op.drop_column("organizations", "excluded_reason")
    op.drop_column("organizations", "excluded_from_analytics")
    # ### end Alembic commands ###
